version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello
hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
